# The three production systems, written in the same shape as the extracted entries.
VENUES = [
 dict(
  slug="venue-integration",
  human_title="Match every booking to what the table actually spent",
  plain_body="My venues take table bookings in one system and ring up sales in another, and neither knows the other exists. This matches them every night, so we can finally answer which tables hit their minimum, who never showed up, and which section made the money.",
  tech_body='Reservations-to-POS reconciliation across <strong>two different POS systems</strong>. A deterministic scoring engine matches each reservation to its check and records why, then reports minimums, no-shows, revenue by section, and deposits.',
  prov="Luna Rooftop and The Lobby",
  impact="Two POS systems, one pipeline",
  live=True,
  tags=["TypeScript","Node 22","SQLite","Toast API","TableList API"],
  plain_pain="Every Saturday morning we pieced together the night before from two printouts by hand, and still got it wrong.",
  pain="The booking system and the POS share no common identifier. A party moves tables, one order carries two checks, and a 1:30am check belongs to the previous business date.",
  plain_solve="One command answers the four questions the owners actually ask, and shows its work for every match it made.",
  solve="A scored matcher pairs reservations to checks and records the reason for every match, so a disputed number can be traced back to the evidence rather than argued about.",
  where="Luna Rooftop and The Lobby Social Bar, nightly",
  steps=[
   'Wrote one <code>PosAdapter</code> interface with two implementations, so a venue picks its POS in config rather than forking the codebase.',
   'Built a <strong>business date</strong> rule into the domain model: the night runs 6pm to 6am, so a 1:30am check belongs to the prior calendar day. Getting this wrong silently splits a night in half.',
   'The matcher scores each candidate on table, time window, party size, and whether the deposit shows up as a tender line, then assigns greedily so one check can never satisfy two reservations.',
   'Every match stores its reasons, and the leftovers surface as no-show, walk-in, or possible split rather than being dropped.',
  ],
  why="Built for the two venues I co-own because the reports we needed did not exist in either vendor's product. It runs against the real APIs and against recorded fixtures, so the whole pipeline runs offline with no credentials.",
  links=[("code","https://github.com/gharvey135/venue-integration","View the code")],
  proto="",
 ),
 dict(
  slug="venue-table-spend-demo",
  human_title="Prove which tables hit their spend minimum",
  plain_body="Bottle service tables agree to spend a minimum. The point of sale system can show you a receipt but it cannot tell you what a whole table spent, so nobody could check. This adds it up per table and shows exactly what they ordered.",
  tech_body='Walks orders to checks to selections and groups by table, because the sales screen only renders the check layer. Every money identity <strong>verified against the live API</strong>, not taken from the docs.',
  prov="Nightly, per business date",
  impact="Verified against the live API",
  live=True,
  tags=["Python","Toast API","Reconciliation"],
  plain_pain="A table can miss its minimum by hundreds of dollars and nobody notices, because no screen adds up a table.",
  pain="The POS model puts money on the check and the table on the order one level up, so the table never appears on the sales screen at all.",
  plain_solve="One command per night, per table: what they spent, whether they cleared the minimum, and every item they ordered.",
  solve="Groups by table across orders, excludes voided and denied payments, and reconciles the money identities so the totals can be trusted against the vendor's own reports.",
  where="Public version of a nightly tool, synthetic data",
  steps=[
   'Verified against a real night that <code>check.amount</code> is item sales <strong>plus</strong> the card surcharge, so the number the vendor UI labels subtotal is not pure product sales.',
   'Found the double-count trap: one check carried a voided payment and a captured payment for the same amount, so naive summing inflates revenue.',
   'Made the spend basis configurable across four definitions, because the answer to "what did they spend" legitimately differs depending on who is asking.',
   'Wrote a reconciliation command that proves the pull is complete and the money identities hold, since the API exposes no sales summary to diff against.',
  ],
  why="The private version runs against a real venue account. This public repo is the same code against a synthetic fixture that reproduces every edge case that bit the original: table moves, split checks, voided payments, and an open check.",
  links=[("demo","https://gharvey135.github.io/venue-table-spend-demo/","See it running"),
         ("code","https://github.com/gharvey135/venue-table-spend-demo","View the code"),
         ("doc","https://github.com/gharvey135/venue-table-spend-demo/blob/main/docs/case-study.md","Read the case study")],
  proto="",
 ),
 dict(
  slug="hr-compliance-automation",
  human_title="Catch expiring certifications before they lapse",
  plain_body="In Texas, a bartender serving on an expired alcohol certification puts the venue's liquor licence at risk. Staff file paperwork as phone photos with inconsistent names. Every week this reads the folder, rebuilds the tracking sheet, and drafts the reminder emails.",
  tech_body='Scanned documents become a one-row-per-employee snapshot in Sheets plus drafted expiry alerts. Runs unattended weekly across <strong>two venues with different folder layouts</strong>, from one config per venue.',
  prov="Weekly since Aug 2026",
  impact="70 employees, 20 contractors",
  live=True,
  tags=["Python","Google Sheets","Apps Script","Scheduled job"],
  plain_pain="A hand-kept spreadsheet drifted from the real files twice. Both times we found out by accident.",
  pain="Documents arrive named three different ways for the same person across four folders, so a hand-maintained sheet cannot stay in sync with the folder it describes.",
  plain_solve="The sheet is rebuilt from the source every week, so it cannot drift, and every expiring certification becomes a draft email a manager only has to send.",
  solve="Rebuild from source rather than update in place, so drift is structurally impossible. Manual inactive marks persist in a separate ledger that survives every rebuild.",
  where="Two venues, weekly, unattended",
  steps=[
   'Hard rule enforced in code and asserted in tests: record <strong>presence flags only</strong>, read from filenames. No identification numbers or dates of birth are ever stored, and the scans are never opened.',
   'Roster comes from the newest scheduling export minus a persistent inactive ledger, so an owner marking someone inactive overrides the export forever.',
   'One config per venue describes that venue\'s folder layout and column set, so two structurally different venues run on one code path.',
   'Certifications inside 30 days become a drafted email grouped by urgency, which a manager reviews and sends. The system never sends on its own.',
  ],
  why="Production for two venues since August 2026. The public repo is the generalized, de-identified version: same code, same sheet layout, same scheduled prompt, with a synthetic roster.",
  links=[("demo","https://gharvey135.github.io/hr-compliance-automation/","See it running"),
         ("code","https://github.com/gharvey135/hr-compliance-automation","View the code"),
         ("doc","https://github.com/gharvey135/hr-compliance-automation/blob/main/docs/case-study.md","Read the case study")],
  proto="",
 ),
]

REPOS = [
 ("integration-patterns","Seven integration primitives with their edge cases written down as tests: signature verification, idempotency keys, retry with backoff, rate limiting, pagination, circuit breaker, transactional outbox.","TypeScript","75 tests"),
 ("api-contract-diff","Compares two versions of an API description and flags every change that would break the people using it. Exits non-zero so it can block a release.","Python","50 tests"),
 ("data-underwriting-example","Five-stage address intelligence pipeline for insurance underwriting. 466 of 500 deliberately corrupted addresses confirmed with zero manual review.","Python","53 tests"),
 ("solutions-playbooks","The documents I actually use across an engagement: discovery question bank with red-flag answers, scoping worksheet, ADRs, runbooks, UAT plans, handoff checklist, escalation playbook.","Markdown","11 docs"),
]
